config.go

Related to https://github.com/getAlby/nostr-wallet-connect-next/issues/12
If the user does not set a password (due to skipping the welcome screen), then the user still needs to be able to unlock

fix: empty password check

---

migrations/202401191539_initial_migration.sql

Deleting apps after using it doesn't work as of now because using the app would populate the `request_events` and `response_events` tables and deletion of app casades the deletion of `app_permissions`, `payments` and `request_events` but the `response_events` which are linked to the `request_events` are not cascaded and that causes the issue.

fix: casade response_events on request_events

---

Dockerfile

since libbreez_sdk_bindings.so  specific version is already present on /go/pkg/mod/github.com/breez/  we can just copy it instead of wget'ing a specific version from github repo

copy libbreez_sdk_bindings.so  instead of wget'ing

---

README.md

The idea is to make it easy for users to run this app in whatever way is convenient for them. These are one-line commands to deploy NWC using docker.

doc: add instructions to deploy with docker to README

---

README.md
config.go
ldk.go
service.go

LDK sometimes becomes unresponsive, I am trying to find out why.
This PR supports LDK and app log levels (which are incompatible due to opposite log level severity directions)

Feat: custom log levels

---

go.mod
go.sum
ldk.go

(Also contains changes from https://github.com/getAlby/nostr-wallet-connect-next/pull/73) 
For any payments that don't have an invoice, the created date is now set to 0 so they will be ordered last

Feat: read bolt11 invoice from LDK payment

---

ldk.go

otherwise it crashes with array out of limit

check if array has at least limit for slice

---

ldk.go
ldk_event_broadcaster.go

https://github.com/getAlby/nostr-wallet-connect-next/pull/89 needs to be merged first
Tested by doing multiple successful multi_pay_invoice commands (each paying 10 invoices in parallel)

Fix: LDK remove mutex

---

ldk.go

example output from JS SDK nwc client:
```
{
alias: 'NWC',
color: '#897FFF',
pubkey: '03c0ceddcfb1339b5c024368444278a3849d71d55c21e4fa81d0a43c0cff6cf99e',
network: 'bitcoin',
block_height: 835732,
block_hash: '000000000000000000029a95a15b781c49ba05915bcacdd6b096211c7bf5ea69',
methods: [ 'get_info' ]
}
```

feat: improve LDK get info response

---

.env.example
README.md
alby/alby.go
alby/alby_http_service.go
api.go
events/event_logger.go
handle_multi_pay_invoice_request.go
handle_multi_pay_keysend_request.go
handle_pay_keysend_request.go
handle_payment_request.go
http_service.go
ldk.go
models/config/config.go
service.go
service_test.go
start.go
wails_app.go

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/52
The current design supports multiple subscribers (if we wanted to also send nostr DMs from the NWC app, and maybe handle events for other purposes e.g. achievements - but I'm not sure here because the event properties are untyped). Events are handled in separate goroutines to be non-blocking.
Go to http://localhost:5173/#/channels/first to connect your Alby account.
This assumes that NWC is actively running and being used so that the refresh token can always be used to get a new access token.
Before the user connects their Alby account, events will fail to be sent.
There are three events fired right now:
- `nwc_started` (currently has no properties - maybe we could include the version number)
- `nwc_unlocked` (http mode …

feat: log events

---

go.mod
go.sum

Fixes #48 
Actually should've been handled by https://github.com/nbd-wtf/ln-decodepay

fix: check for ln prefix and number before decoding

---

api.go

Currently we only check the first item in the array

fix: check other items in the array for clearnet

---

api.go
http_service.go
wails_app.go

Doesn't make sense to pass `svc` and also pass `svc.AlbyOAuthSvc`, and especially when `svc.AlbyOAuthSvc` is only being used twice in NewAPI methods

chore: only pass svc to NewAPI

---

api.go
breez.go
frontend/src/screens/channels/MigrateAlbyFunds.tsx
greenlight.go
http_service.go
ldk.go
lnd.go
models/api/api.go
models/lnclient/lnclient.go
service_test.go
wails_handlers.go

This exposes onchain balances as well as useful lightning information regarding ingoing and outgoing liquidity. Not all values need necessarily be exposed in the UI.
Also fixes breez balance to only show the spendable amount
Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/181

feat: api call to get onchain and lightning balances

---

api.go

Breez was broken due to the forced onboarding to get your first channel. I think we need a better solution for this, but I just did the minimum fix for now. This also needs to be considered for Phoenixd (not in master).

fix: do not require channel in onboarding for breez backend

---

.env.example
alby/alby.go
models/config/config.go

Auto-connecting in local development causes the current getalby.com connection to break. So I have added an env variable to be able to disable it (but it's enabled by default)

chore: add config option to disable connecting alby account to NWC

---

.github/workflows/package-raspberry-pi.yml
scripts/install.sh
scripts/update.sh

Executable permissions are not preserved in zip files.

fix: pi install script

---

breez.go
go.mod
go.sum
greenlight.go
handle_multi_pay_invoice_request.go
handle_payment_request.go
ldk.go
ldk_event_broadcaster.go
lnd.go
models.go
models/lnclient/lnclient.go
service.go
service_test.go

TODO:
This adds fees for the LDK node type to:
- pay_invoice
- list_transactions
- lookup_invoice
It also removes the preimage check in the budget calculation as a small step towards https://github.com/getAlby/nostr-wallet-connect-next/issues/279
the ldk-node-go update also penalizes routes with longer hops, resulting in more reliable payments

feat: add payment fees to ldk + penalize routes with more hops, remove preimage check from budget calculation

---

alby/alby_http_service.go

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/290

fix: remove alby http oauth callback redirect for default oauth client

---

api.go
frontend/src/screens/channels/Channels.tsx
frontend/src/screens/settings/DebugTools.tsx
go.mod
go.sum
http_service.go
ldk.go
main_http.go
models/lnclient/lnclient.go
wails_handlers.go

- add force close channel option
- remove reference to LDK node at start of shutdown so it cannot be interacted with
- call LDK stop with 30 second timeout
- move reset router logic to Go after LDK node is shut down
- add button to debug tools to get balances
- update ldk-node to latest changes on tnull's anchor support branch
TODOs:

fix: LDK shutdown

---

api.go
breez.go
go.mod
go.sum
greenlight.go
http_service.go
ldk.go
lnd.go
models/lnclient/lnclient.go
service_test.go
wails_handlers.go

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/316
Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/315
The LDK-node updates make shutdown more likely to finish safely, reduce chance of blocking/deadlocks while sync is running, and increase some sync timeouts to ensure the sync finishes as much as possible.
The router reset is done to reduce the size of the ldk node DB, and the router data is not essential which can be re-calculated once the node is started again.

feat: reset router when backing up node, update ldk-node dependency

---

ldk.go

Existing node info could not be used because we only store pubkeys. This list will need to be maintained and I'm not sure we can do this long term. Update: this is probably only needed until LDK p2p gossip interoperability with CLN and Eclair is fixed.

feat: connect some peers at LDK node startup for p2p gossip

---

api.go
frontend/src/hooks/useSyncWallet.ts
frontend/src/screens/channels/Channels.tsx
frontend/src/screens/channels/CurrentChannelOrder.tsx
go.mod
go.sum
http_service.go
ldk.go
service.go
wails_handlers.go

In this change the NWC app will handle syncing the LDK wallet itself (rather than it originally happening in the background).
The LDK wallet always syncs immediately at startup (and the polling hack was removed!). If the initial sync fails, then the lnclient will not be started.
There's two sync times:
- Default: once per hour
- Frequent: once per minute (only when opening a new channel or on the channels/liquidity page)
On shutdown, I also ensure the current sync is completed before calling the actual LDK node shutdown method.
TODOs:

feat: dynamic wallet sync intervals based on user activity

---

lnclient/ldk/ldk.go

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/168
Keysend payments were filtered out due to missing created at. Also added other missing properties: settled_at, payment_hash, preimage

fix: include keysend payments in ldk list_transactions

---

db/models.go
migrations/202405302121_store_decrypted_request.go
migrations/migrate.go
service.go

this allows use to create an event log in the future and list the actual requests per app connection

Store decrypted request method and content data

---

frontend/src/screens/channels/Channels.tsx

Closes #272 
Adds "View Funding Transaction" in the dropdown of each channel row to view the transaction on mempool

chore: add view funding transaction

---

db/models.go
migrations/202406061259_delete_content.go
migrations/migrate.go
service.go
service_test.go

Fixes #328 
Removes content from `request_events` and `response_events`
⚠️ This does not add `contentData` to `response_events` (like it is done in `request_events` table in #359) so now we don't store anything content-related from the response

chore: add migration to remove content

---

migrations/202406061259_delete_content.go

Adds vacuum post the migration (follow up to #392 merged just now)

chore: add vacuuming after migration

---

frontend/src/App.tsx
frontend/src/screens/Welcome.tsx
frontend/src/screens/setup/node/PresetNodeForm.tsx

This PR re-allows you to setup your node via env variables, and have one click to get started with a different node backend than LDK.

fix: support preset node from env in new node selection UI

---

migrations/202406071726_vacuum.go
migrations/migrate.go
service.go

Closes https://github.com/getAlby/nostr-wallet-connect-next/issues/398

fix: enable auto vacuum to ensure DB does not grow infinitely

---

go.mod
go.sum
lsp/lsp_service.go

For LSPS1 public channels, as per BOLT-7 6 confirmations are required for the channel to be gossiped. So to make the UX flow nice (especially for podcasters) it makes sense to only mark the channel as active after 6 confirmations.
Supposedly LDK should add public route hints before that, but it won't work for podcasting and doesn't seem to work for normal invoices either.
This also enables simultaneous 0-conf and non-0-conf support for a couple of whitelisted LSP nodes (Olympus and Megalith). See https://github.com/getAlby/ldk-node/commit/fe5cc20eb1dd3dcb7dc576b01e5e3081839d7b63 (as a workaround until the LND bug is fixed - this is only needed for LSPs which we want both 0-conf and non-0-conf)

Fix: LSPS1 public 6 confirmations, LND simultaneous support 0-conf and non-0-conf

---

.github/workflows/wails2.yaml

This embeds the webview dependency which will be used if the webview is not available. 
Otherwise the user would get prompted to download it and I thought this is easier. 
https://wails.io/docs/guides/windows/

Embed webview if not available

---

go.mod
go.sum
lnclient/ldk/ldk.go

This enables NWC apps that display transactions to show podcasting 2.0 details
See https://github.com/getAlby/lightning-browser-extension/pull/3172 for how it is consumed.
Note: this is inconsistent with how the TLVs are passed in https://github.com/nostr-protocol/nips/blob/master/47.md#pay_keysend
In retrospect I think this should actually be changed to be `metadata.tlv_records` and have the same format as `pay_keysend`

feat: add ldk custom tlvs to metadata custom records

---

lsp/lsp_service.go

fix: respect LSPS1 channel max expiry blocks

---

api/api.go
api/models.go
frontend/src/screens/channels/Channels.tsx
frontend/src/types.ts
http/http_service.go
lnclient/breez/breez.go
lnclient/cashu/cashu.go
lnclient/greenlight/greenlight.go
lnclient/ldk/ldk.go
lnclient/lnd/lnd.go
lnclient/lnd/wrapper/lnd.go
lnclient/models.go
lnclient/phoenixd/phoenixd.go
tests/mock_ln_client.go
wails/wails_handlers.go

Users can now update base forwarding fees on public channels. A high value can be set to prevent routing.

feat: update channel

---

events/models.go
frontend/src/components/EmptyState.tsx
lnclient/ldk/ldk.go
nip47/controllers/get_info_controller.go
nip47/controllers/get_info_controller_test.go
nip47/notifications/models.go
nip47/notifications/nip47_notifier.go
nip47/notifications/nip47_notifier_test.go
nip47/permissions/permissions.go
tests/mock_ln_client.go

- refactor to better support multiple notification types
- remove unnecessary properties in `payment_received` and `payment_sent` events
- ~~duration is wrong, I need to remove it or rename it (since it's the duration since the invoice was created)~~ - removed the duration property for now
- When originally implementing notifications which was that "notifications" was being returned in the methods parameter of the get_info call and we didn't even include what notification types are supported there (which would be empty if you don't allow the notifications permission).
`get_info` now looks like this:
```
{
alias: 'NWC',
color: '#897FFF',
pubkey: '0219b1a2bf969944e941f72595db5a5dd55531db00972d41bf8099e499dcaea894',
network: 'signet',
block_height: 1190784,
block_hash: …
```

Chore: payment sent notification improvements

---

go.mod
go.sum
lnclient/ldk/ldk.go

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/496
Updates fee estimates once per minute rather than once per hour by default

fix: frequently update fee estimates

---

alby/alby_oauth_service.go

Possibly fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/408

fix: only use current access token if it expires 20+ seconds in the future

---

frontend/src/components/layouts/AppLayout.tsx

This is the case with the docker builds because they are tagged as latest before the release is published

fix: if version is greater than released version, still mark Alby hub as up to date

---

.github/workflows/build-docker.yaml
Dockerfile

This seems to be a known issue people experience often: https://github.com/nodejs/docker-node/issues/1335

fix: increase yarn timeout in Docker image to fix failing arm64 builds

---

.github/workflows/http.yml

to keep it always the same and bz2 is smaller than gz

chore: create bz2 archives in http build

---

.github/workflows/build-docker.yaml
.github/workflows/http.yml
.github/workflows/wails.yml
go.mod

This is intended to ensure consistency of Go versions in go.mod and in Github actions and releases, as well as to fix tar warnings originating from the setup-go action:
```
Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
```
The workaround, as suggested by https://github.com/actions/setup-go/issues/424, is to use exactly the same version of Go in the Github actions as the one specified in go.mod.
Additionally, this PR removes the `toolchain` directive from go.mod as unneeded (and it also causes the tar error mentioned above)

fix: use Go version from go.mod in Github actions

---

frontend/src/screens/channels/CurrentChannelOrder.tsx

Our new design (which we haven't implemented yet) also does not cover this useful info.
I need help with the design (It will take time to implement the new channel opening design)

feat: add extra info to the channel opening page

---

frontend/src/components/SidebarHint.tsx
frontend/src/screens/channels/Channels.tsx
frontend/src/types.ts
lnclient/greenlight/greenlight.go
lnclient/ldk/ldk.go
lnclient/lnd/lnd.go
lnclient/models.go

This PR adds alerts to the liquidity page when something needs to be reviewed by the user so they understand why payments might be failing.
No UI changes when your channels are healthy.
- fix: LDK local balance not including amount in reserve
- show current reserve amount if unmet
- unmet channel reserve alert
- low receiving capacity alert
- unbalanced channel warnings
- fix: new channel order sidebar hint not showing on liquidity page

feat: channel liquidity alerts on liquidity page

---

.github/workflows/http.yml

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/549

fix: add version tag to linux http executables

---

scripts/install.sh

We know it's a hack, but have no better solution for RPI right now.

fix: ensure alby hub never uses more than 90% cpu (on RPI zero)

---

frontend/src/screens/wallet/index.tsx

chore: remove balance cards in wallet screen

---

frontend/src/screens/channels/Channels.tsx

`mb-5` is just added to keep the sats in other cards in the same line as Savings Balance sats, if this feels hacky, we can group Header and Content in a div and add `flex flex-col justify-between` to the `<Card>`

chore: push card footer to bottom
