getAlby/nostr-wallet-connect-next

api.go
frontend/src/screens/setup/SetupWallet.tsx

fix: support pre-configured node flow

---

README.md
README_GREENLIGHT.md
api.go
config.go
frontend/src/screens/setup/SetupNode.tsx
frontend/src/types.ts
greenlight.go
models/api/api.go
models/greenlight/greenlight.go
service.go

feat: greenlight LNClient WIP

---

aesgcm.go
api.go
breez.go
lnd.go
service.go
service_test.go
start.go
wails_handlers.go

Follows go code practices to remove those warnings in VS Code

chore: remove go warnings

---

models.go

fix: NIP-47 capabilties does not follow spec

---

config.go
ldk.go
service.go

this allows setting a LDK_NETWORK, LDK_ESPLORA_SERVER, LDK_GOSSIP_SOURCE env variable to configure the network
this is a breaking change as it is using now network specific directories. Is it OK to require moving the current dir, or should we make this backwards compatible

Add support for configurable LDK network

---

ldk.go

Works, but we need to wait for custom TLVs to be merged into ldk-node and ldk-node-go updated

feat: ldk keysend custom tlvs

---

frontend/src/screens/channels/Channels.tsx
frontend/src/screens/channels/NewCustomChannel.tsx
frontend/src/types.ts
greenlight.go
ldk.go
models/lnclient/lnclient.go

Also makes channel creation private by default, and adds a confirmation when creating a public channel

feat: show if a channel is public or private on channels page (LDK)

---

api.go
breez.go
frontend/src/components/BreezRedeem.tsx
frontend/src/screens/channels/Channels.tsx
frontend/src/screens/channels/RecommendedChannels.tsx
frontend/src/types.ts
greenlight.go
ldk.go
lnd.go
models/api/api.go
models/lnclient/lnclient.go
service_test.go

Partially addresses https://github.com/getAlby/nostr-wallet-connect-next/issues/110

feat: show pending onchain balance

---

api.go
frontend/src/components/Navbar.tsx
frontend/src/components/redirects/SetupRedirect.tsx
frontend/src/screens/Start.tsx
frontend/src/screens/setup/SetupPassword.tsx
http_service.go

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/99

fix: do not allow user to re-setup their node after setup is completed

---

ldk.go
models/lsp/lsp.go

add Alby Plebs LSP node PubKey to TrustedPeers0conf & AnchorChannelsConfig.TrustedPeersNoReserve

Alby Plebs LSP 

---

api.go
frontend/src/screens/channels/Channels.tsx
http_service.go
wails_handlers.go

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/151

feat: add button to stop the node

---

frontend/src/App.tsx
frontend/src/components/redirects/BackupRedirect.tsx

Adds backup redirect to redirect users to welcome screen if setup is not complete.

chore: add backup redirect

---

handle_balance_request.go
handle_info_request.go
handle_list_transactions_request.go
handle_lookup_invoice_request.go
handle_make_invoice_request.go
handle_multi_pay_invoice_request.go
handle_multi_pay_keysend_request.go
handle_pay_keysend_request.go
handle_payment_request.go
models.go
service.go
service_test.go

This adds methods to refactor haspermission and unmarshalling payload in each method
Also returns Nip47Response when bad requests are sent.
Removes err return from handlers and makes sure the user receives an Nip47Response in every scenario

chore: refactor haspermission and unmarshal checks

---

events/event_logger.go
models/config/config.go
service.go
service_test.go

Fixes https://github.com/orgs/getAlby/projects/20?pane=issue&itemId=57961050
Also needs change in getalby.com backend to set `LOG_EVENTS` to `true`

feat: conditionally turn on event logs

---

.env.example
alby/alby.go
alby/alby_http_service.go
frontend/src/App.tsx
frontend/src/components/redirects/HomeRedirect.tsx
frontend/src/screens/alby/AlbyAuthRedirect.tsx
models/config/config.go

- fixes dev redirect (as long as you set the variable in your .env)
- smoother redirect to alby auth page

feat: improved alby auth redirect

---

ldk.go

Temporary workaround for https://github.com/getAlby/nostr-wallet-connect-next/issues/206

fix: delete old ldk log files on startup

---

api.go

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/180

fix: add error handling for 0-conf api calls

---

frontend/src/types.ts
models.go
nip47_notifier.go
nip47_notifier_test.go
service.go

also change notifications permission name to "notifications"
https://github.com/nostr-protocol/nips/pull/1164

feat: include supported notification types in wallet service info notifications tag

---

frontend/src/screens/onchain/NewAddress.tsx

1. fix styles 
2. migrate to shadcn

fix: onchain-address screen ui

---

api.go

fix: use expiresAtValue instead of empty expiresAt

---

ldk.go

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/200
Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/237

fix: wait for LDK wallet onchain wallet to sync before completing node startup

---

ldk.go

filtering and pagination is done in NWC because LDK does not support it yet

feat: add ldk pagination and filtering, support unpaid parameter

---

frontend/index.html
frontend/src/components/layouts/AppLayout.tsx

This adds a Live Support navigation entry which triggers the chat.

Hide Chatwoot help icon by default

---

frontend/src/App.tsx
frontend/src/screens/channels/Channels.tsx
frontend/src/screens/peers/ConnectPeer.tsx

This allows users to manually connect to a peer independent of opening a channel

Add support to manually connect to peers

---

api.go
frontend/src/App.tsx
frontend/src/screens/channels/Channels.tsx
frontend/src/screens/peers/ConnectPeer.tsx
frontend/src/screens/wallet/SignMessage.tsx
frontend/src/types.ts
http_service.go
models/api/api.go
wails_handlers.go

this is helpful in the case you need to proof ownership of the node.
I did not know where to better put the link.

Add UI to sign a random message with the node key

---

api.go
breez.go
frontend/src/screens/settings/DebugTools.tsx
greenlight.go
http_service.go
ldk.go
lnd.go
models/lnclient/lnclient.go
service_test.go
wails_handlers.go

Check your node status from the debug tools page

feat: add node status debug api call

---

scripts/install.sh
scripts/update.sh

this way we have a fixed fullpath independent of the current user

Move PI albyhub insallation to /opt/albyhub

---

scripts/install.sh

currently we start it too early

Start NWC after the network is actually online

---

api.go
breez.go
frontend/src/screens/settings/DebugTools.tsx
go.mod
go.sum
greenlight.go
http_service.go
ldk.go
lnd.go
models/api/api.go
models/lnclient/lnclient.go
service_test.go
wails_handlers.go

Also fixes LDK-node bugs (graceful shutdown fix for stopping event handler, fix signing anchor transaction for bump transaction, reuse last unused address rather than generating new ones)
TODOs:

feat: update ldk-node version, add button in debug tools to fetch network graph

---

frontend/src/screens/setup/SetupPassword.tsx

feat: update set unlock password screen designs

---

.vscode/extensions.json

What other extensions to include?

feat: add recommended extensions

---

go.mod
go.sum

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/373
Uses ldk-node change https://github.com/getAlby/ldk-node/pull/28

fix: received keysend payment last updated time

---

lnclient/ldk/ldk.go

This PR correctly calculates the reason message for channel closures and failed channel opens.

fix: correctly handle channel closure reason

---

frontend/src/screens/wallet/index.tsx

fix: hide alby extension banner if already installed

---

frontend/src/components/layouts/SettingsLayout.tsx
lnclient/ldk/ldk.go

I avoided adding new page or new text elements for shutdown. cause for http mode its very fast. we we still loading states in few situations as mentioned in issue
Fixes #368

feat: loading state for shutdown button

---

api/api.go
api/esplora.go
api/models.go
config/models.go
frontend/src/constants.ts
frontend/src/hooks/useOnchainAddress.ts
frontend/src/screens/channels/CurrentChannelOrder.tsx
frontend/src/screens/onchain/BuyBitcoin.tsx
frontend/src/screens/onchain/DepositBitcoin.tsx
frontend/src/types.ts
http/http_service.go
wails_handlers.go

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/384

chore: move address storage to backend and return last unused address

---

lnclient/ldk/ldk.go
lsp/lsp_service.go
lsp/models.go

LSPS1 LSP for incoming liquidity with 0-conf and minimum size of 20,000 sats.
https://docs.megalithic.me/

feat: add megalith LSP

---

frontend/src/screens/channels/CurrentChannelOrder.tsx
frontend/src/screens/channels/NewChannel.tsx
frontend/src/screens/onboarding/MigrateAlbyFunds.tsx
frontend/src/types.ts
lsp/lsp_service.go
lsp/models.go

Closes https://github.com/getAlby/nostr-wallet-connect-next/issues/422

feat: support public channels for lsps1

---

frontend/src/lib/clipboard.ts

Partially fixes #425
Fixes `copyToClipboard` not working in non-HTTPS mode

fix: copyToClipboard selection

---

frontend/src/screens/wallet/OnboardingChecklist.tsx

Hides the checklist while loading and if everything is checked ✅

fix: hide checklist by default

---

lnclient/lnd/lnd.go
lnclient/lnd/wrapper/lnd.go

To be merged in #457 
Adds UpdateChannel to LND

feat: add update channel in lnd

---

lnclient/lnd/lnd.go

Fixes #444 
Adds TLV records in metadata of the transaction

feat: add tlv records in lnd

---

.github/workflows/build-docker.yaml
.github/workflows/package-raspberry-pi.yml
.github/workflows/wails.yml
Dockerfile
README.md
api/api.go
api/models.go
frontend/src/components/layouts/AppLayout.tsx
frontend/src/components/layouts/TwoColumnFullScreenLayout.tsx
frontend/src/types.ts
service/service.go
version/version.go

version is passed to the go app at build time

Feat: version display

---

api/lsp.go

There's some inconsistencies in the merged PR that need to be resolved first
Fixed in https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/118

fix: update LSPS1 to match latest spec changes

---

go.mod
go.sum
lnclient/ldk/ldk.go

Closes https://github.com/getAlby/nostr-wallet-connect-next/issues/485

chore: update LDK-node dependency to v0.3.0

---

frontend/src/components/layouts/AppLayout.tsx

feat: feedback link

---

lnclient/ldk/ldk.go

so it also applies on counterparty-initiated channels
Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/494

fix: set high default forwarding fee on channel ready event

---

frontend/src/screens/channels/Channels.tsx

fix: order channels by size

---

frontend/src/screens/channels/Channels.tsx

Also updates the verb to "transfer"

fix: liquidity check before transferring funds from alby shared node

---

.github/workflows/build-docker.yaml
.github/workflows/http.yml
README.md
nip47/controllers/multi_pay_invoice_controller_test.go
nip47/controllers/multi_pay_keysend_controller_test.go

chore: fix race condition in multi_ tests by adding mutex

---

frontend/src/screens/channels/IncreaseIncomingCapacity.tsx
frontend/src/screens/channels/IncreaseOutgoingCapacity.tsx
frontend/src/types.ts

Closes https://github.com/getAlby/nostr-wallet-connect-next/issues/509

Feat: simplify open channel UI

---

api/lsp.go
utils/utils.go

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/528

fix: exclude tor uris from lsps1 info response

---

frontend/src/screens/channels/CurrentChannelOrder.tsx
frontend/src/screens/wallet/Send.tsx

Fixes https://github.com/getAlby/nostr-wallet-connect-next/issues/511

feat: pay lsps1 orders with internal wallet

---

scripts/install.sh
scripts/update.sh

chore: use official download url for pi install

---

frontend/src/components/connections/AlbyConnectionCard.tsx
frontend/src/components/connections/AppCardConnectionInfo.tsx
frontend/src/screens/apps/ShowApp.tsx

Also fixes Set Budget button leading to nowhere in Connections Screen (when no budget is set for getalby.com)

feat: support edit param in show app screen

---

frontend/src/screens/onboarding/MigrateAlbyFunds.tsx

Other node implementations might fail, we don't have resources to support this. This does not block users migrating their funds (see the comment in the changes)

fix: only allow using alby shared balance to fund a channel if running LDK backend
